target "EarBook" do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.0'
pod 'Masonry', '~> 1.0.1'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh', '~> 3.1.0'
pod 'UMengSocialCOM', '~> 5.2.1'
end
